
# ServerProperties
server:
  port: 60129
  context-path: /hospital/rs
  error.include-stacktrace: on_trace_param
  session.timeout: 86400  # 24 小时

# ResourceServerProperties
security.oauth2.resource:
  filterOrder: 90

# SecurityProperties
security:
  basic.enabled: false

# LOGGING
logging:
  path: /data0/store/app/qh-bargain/qh-bargain-server/logs/
  level:
    root: INFO


# SessionProperties
spring.session:
    store-type: JDBC


# DevToolsProperties

# AuthorizationServerProperties

# JacksonProperties
spring.jackson:
  default-property-inclusion: non_absent

# EMBEDDED SERVER CONFIGURATION (ServerProperties)
server.tomcat:
  remote-ip-header:       X-Forwarded-For
  protocol-header:        X-Forwarded-Proto
  uri-encoding:           UTF-8


spring.jersey:
  application-path: /api
  type: servlet
  servlet.load-on-startup: 0



spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hospital
      username: root
      password: 123456
      initialize: true
  jpa:
      database: MYSQL
      show-sql: true
      hibernate:
        ddl-auto: create-drop

